name: clario_test_project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  get_it: ^8.0.3
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  equatable: ^2.0.7
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700

        
  

